---
- name: Scan subnet for active hosts
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Scan the subnet for live hosts
      ansible.builtin.shell: "nmap -sn 192.168.1.0/24"
      register: nmap_output

    - name: Extract live hosts from nmap output
      ansible.builtin.debug:
        var: nmap_output.stdout_lines
